### ISSUE TITLE
Page blank in My workspace

### ISSUE THREAD

**Issue by totolook** [gremlfiy/gremlify#1]
Hi all,
i have an account with graphs saved in workspace but,  when i click 'My workspace' the page is blank and the console show up this message: 
```js
TypeError: can't access property "toString", e.id is undefined
```
In particularity in
 
`DagreLayout.ts`
```ts
 nodes.forEach((n) => {
      this.g.setNode(n.id.toString(), {
        width: this.options.nodeWidth,
        height: this.options.nodeHeight,
      });
    });
```

I debugged the page at this point, i have a impression than graphes aren't loading

```ts
//GraphUtils.ts
 /**
   * generate a graph with a given layout engine
   * @param layoutType
   * @param graph
   */
  public static generateGraphFromLayout(
    layoutType: LayoutType | null,
    graph: IGraph
  ) {
    const layout = LayoutFactory.create(
      layoutType ? layoutType : DEFAULT_LAYOUT
    );
    return layout.buildLayout(graph); // graph is undefined!
  }

``` 

![immagine](https://user-images.githubusercontent.com/10384062/85265104-0ae0d680-b472-11ea-9c85-1fbf5f8af938.png)

**Comment by gremlify** [comment]
@totolook Thanks, we will take a look ASAP.

**Comment by gremlify** [comment]
Hey @totolook, this should be fixed by now :)

Please let us know if you still face this issue, or any other.
We'll wait for your response to close.

**Comment by totolook** [comment]
it's work! Thank you.
