### ISSUE TITLE
Schema edges with same name makes Graph unable to connect vertices using the given edge

### ISSUE THREAD

**Issue by matbhz** [gremlfiy/gremlify#12]
When you create a _schema_ with a few different vertices and those vertices are connected by edges with the same name, the _graph_ does not allow you to connect actual vertices using the edges defined in the schema

Let's take the following example (the number indicates the order of events executed):

SCHEMA:

```
1. (A) ---- contains -----> (B)
2. (B) ---- contains -----> (C)
```

GRAPH

```
3. (A)
4. (B)
5. (C)
6. (B) ---- contains ---> (C) // Works
7. (A) ---- contains ---> (B) // Schema validation error: Invalid edge 'contains' between 'A' and 'B'

```

Screenshots:

![image](https://user-images.githubusercontent.com/3178095/100019011-3d309000-2d92-11eb-9f5a-1c866f42aa52.png)
![image](https://user-images.githubusercontent.com/3178095/100019083-59343180-2d92-11eb-8ff8-379c2968d3bc.png)

**Comment by gremlify** [comment]
This is now fixed, thanks for reporting this @matbhz !
