### ISSUE TITLE
Expired TLS certificates on gremlify.com

### ISSUE THREAD

**Issue by joeapearson** [gremlfiy/gremlify#14]
Looks like the TLS certs on gremlify.com expired yesterday on the 25th of Jan.  Any chance they can be renewed?

![image](https://user-images.githubusercontent.com/5048649/105899765-f0ef0f80-5fcf-11eb-8d37-35886f199bf1.png)

**Comment by joeapearson** [comment]
Either there was a temporary issue on my end or they've just been fixed.  Thanks!  Closing.

**Comment by gremlify** [comment]
Hey @joeapearson! 
There was a problem indeed, we fixed it last night.
