### ISSUE TITLE
Internal Server Error when clicking "Add To Favorites"

### ISSUE THREAD

**Issue by davidcava** [gremlfiy/gremlify#15]
I don't seem to be able to save my queries, I always get this Internet Sever Error message when clicking on Save, be it on Chrome, Firefox, having renamed the query first or whatever I tried

**Comment by kadoshms** [comment]
Thanks for reporting this, I'll take a look on this one as soon as possible.

**Comment by kadoshms** [comment]
@davidcava hey, I'm not able to reproduce this - could you please add some more details to the ticket?

**Comment by davidcava** [comment]
For example in my workspace, clicking on Add to favorite triggers the error:  https://gremlify.com/fjiprz05je/8

**Comment by kadoshms** [comment]
Yes I can see that, thanks.
Looks like the Schema has to be altered to support longer queries. Great catch.

**Comment by kadoshms** [comment]
Fixed that, thanks for reporting.
