### ISSUE TITLE
Number parsing

### ISSUE THREAD

**Issue by vanhumbeecka** [gremlfiy/gremlify#2]
Hi there, I came across a possible issue.
When trying out a recipe from the tinkerpop website, I tried to do a query which involves taking the sum of numbers in property values.

However, I'm constantly getting "java.lang.String cannot be cast to java.lang.Number"

The query I'm trying to execute is
```
g.V(7665)
    .repeat(out().simplePath()).until(hasId(7645))
    .path().by(constant(0)).by('weight').map(unfold().sum())
```
where each node in the graph has a `weight` property with a whole number.

What am I missing?

**Comment by gremlify** [comment]
Hey @vanhumbeecka!

I believe you meant to run `repeat(outE().inV().simplePath())`, this will give you the path edges.
Also, we tried to reproduce this error here, but without success:

https://gremlify.com/9shdthinsjc

Can you please save your workspace and share it here?

**Comment by vanhumbeecka** [comment]
Oh ok, now i think i understand. The `by` targets the elements inside the `repeat` in order, so there wasn't a second target for the `weight`. So my query was bogus. Thanks for the example.

Fyi, the link the workspace is https://gremlify.com/7te2zd2a99m/4
(The weights are part of the nodes instead of relations)
Running the query gives the cast exception.
