### ISSUE TITLE
Please add support for comments

### ISSUE THREAD

**Issue by fermmm** [gremlfiy/gremlify#3]
Reasons:
1. To communicate
2. To be able to copy paste queries from the project without the extra effort of removing comments and then re-adding them again when copying back to the project

**Comment by gremlify** [comment]
Hey @fermmm thanks for reaching us out.
It's a great suggestion, we will defiantly add support for comments.
Please follow up here.

**Comment by gremlify** [comment]
Hey @fermmm , we added support for single-line comments, take a look here:
https://gremlify.com/mznuieoyz3

Have a great weekend!
