### ISSUE TITLE
Strange error in traversal query

### ISSUE THREAD

**Issue by kuzeko** [gremlfiy/gremlify#5]
Hi,

I'm using the `Ego-Alter graph`.
I've tried first this query:

```
g.V().hasId(17108).outE().outE().outE().where(otherV().hasId(17108)).count()
```

which correctly returns

```
[
  0
]
```

then I tried this:

```
g.V().hasId(17108).bothE().bothE().bothE().where(otherV().hasId(17108)).count()
```

but it returns:
```
{
  "error": "Error encountered evaluating script: g.V().has('_gremlify_graph_id','076f5663f34890af3618950c1b29c5755442c3af9fb3de5e1bfeba17b333cd8a').hasId(17108).bothE().bothE().bothE().where(__.otherV().hasId(17108)).count()"
}
```

Any idea what is going on?

**Comment by gremlify** [comment]
Hey @kuzeko thanks for reaching us out.

It seems like there is a problem in the query you provided, as you tried to execute the `bothE` step 3 times in a row, which only works on a vertex, and therefore both the second and third `bothE` fail.

Did you mean to run `both().both().bothE()` instead?

**Comment by kuzeko** [comment]
Thanks a lot!
Actually this is interesting, I was using gremlify to test a query that was failing in my java implementation.
Apparently in Java `bothE().bothE().bothE()` is legal, but as you say, it should not! 👍 My bad

**Comment by spmallette** [comment]
It's legal to the compiler, but not at runtime. That's a bit of a quirk of the design to get used to. Any step can follow any other step.
