### ISSUE TITLE
Please add a "graph restarting" feature

### ISSUE THREAD

**Issue by fermmm** [gremlfiy/gremlify#7]
When my query adds or modifies vertices, edges or properties the graph is modified permanently, this behavior is uncomfortable.
When I want to execute my query again to see the effects of it again, what I have to do is manually remove everything added or modified by the previous execution of the query, item by item, this is very time consuming.

I can click "save" and then go back to the original graph refreshing the browser, but that restarts also my query, so I have to also copy my query before refreshing, it's less uncomfortable but is still uncomfortable because executing the query again it's a very frequent action, it should be as confortable as possible, without many clicks required.

Maybe we can have a button to remove changes made by the last query execution, or something like "Graph templates" with our own graph in order to be able to restart the graph, or maybe a button that restores the graph to how it was when the "save" button was pressed. Whatever is confortable and not time consuming please.

**Comment by gremlify** [comment]
Hey, sounds like an interesting idea.
Indeed currently the best way of doing so is by using "save" and reloading the graph.
We will consider having this functionality in our product in some way.
Thanks!

**Comment by gremlify** [comment]
Hey @fermmm!

We added a **lean** version of this functionality:

![image](https://user-images.githubusercontent.com/62941194/89756524-7434ab80-daeb-11ea-8036-357dd378e35a.png)

We basically added a new "**Revert**" button which by pressing it, will revert the workspace graph to it's last known state (revision).
I must note that this implies that entities will be assigned with new ids, but from your description, it sounds like it might do the work for you.

Anyway, we are working these days on something big that we believe that might also have very positive affects on this feature as well.

We'd love to hear your feedback!

**Comment by fermmm** [comment]
It seems to work perfectly, thanks!
