### ISSUE TITLE
Please optimize a query

### ISSUE THREAD

**Issue by bittu9595** [gremlfiy/gremlify#8]
I have a query like 

g.V().hasLabel('Location').has('id','Europe').out().hasLabel('airport').has('id',within('a','b',...)).out().hasLabel('Staff')

This query gives timeout error when there are large numer of airport id. This query almost take 8-10 sec to execute assuming the location is Europe and now in europe there are 1000s of airports

Please help me optimize this query

**Comment by gremlify** [comment]
Hey There 😄
I'd suggest you to ask this question in stackoverflow since it is more of a Gremlin question rather than a Gremlify one :)

Anyway, Gremlify runs on top of TinkerPop, it might be an issue there.
