### ISSUE TITLE
Please add support for key-values in inject()

### ISSUE THREAD

**Issue by fermmm** [gremlfiy/gremlify#9]
Please support this syntax since it's very common:
`g.inject([[name: "Macka", age: 29]])`

Or like in many languages where is written this way:
`g.inject([{name: "Macka", age: 29}])`

**Comment by gremlify** [comment]
Hey @fermmm , we will investigate the issue when possible. Thanks!

**Comment by gremlify** [comment]
This is supported now 🥳
